// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/VasySS/segoya-backend/internal/dto"

	mock "github.com/stretchr/testify/mock"
)

// MultiplayerUsecase is an autogenerated mock type for the MultiplayerUsecase type
type MultiplayerUsecase struct {
	mock.Mock
}

// NewGame provides a mock function with given fields: ctx, req
func (_m *MultiplayerUsecase) NewGame(ctx context.Context, req dto.NewMultiplayerGameRequest) (int, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for NewGame")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.NewMultiplayerGameRequest) (int, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.NewMultiplayerGameRequest) int); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.NewMultiplayerGameRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMultiplayerUsecase creates a new instance of MultiplayerUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMultiplayerUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MultiplayerUsecase {
	mock := &MultiplayerUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
