// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	DeleteDiscordOperation             OperationName = "DeleteDiscord"
	DeleteUserSessionOperation         OperationName = "DeleteUserSession"
	DeleteYandexOperation              OperationName = "DeleteYandex"
	DiscordLoginOperation              OperationName = "DiscordLogin"
	DiscordLoginCallbackOperation      OperationName = "DiscordLoginCallback"
	EndSingleplayerGameOperation       OperationName = "EndSingleplayerGame"
	EndSingleplayerRoundOperation      OperationName = "EndSingleplayerRound"
	GetLobbiesOperation                OperationName = "GetLobbies"
	GetLobbyOperation                  OperationName = "GetLobby"
	GetMultiplayerGameOperation        OperationName = "GetMultiplayerGame"
	GetMultiplayerGameGuessesOperation OperationName = "GetMultiplayerGameGuesses"
	GetMultiplayerRoundOperation       OperationName = "GetMultiplayerRound"
	GetOAuthProvidersOperation         OperationName = "GetOAuthProviders"
	GetPrivateProfileOperation         OperationName = "GetPrivateProfile"
	GetPublicProfileOperation          OperationName = "GetPublicProfile"
	GetSingleplayerGameOperation       OperationName = "GetSingleplayerGame"
	GetSingleplayerGameRoundsOperation OperationName = "GetSingleplayerGameRounds"
	GetSingleplayerGamesOperation      OperationName = "GetSingleplayerGames"
	GetSingleplayerRoundOperation      OperationName = "GetSingleplayerRound"
	GetUserSessionsOperation           OperationName = "GetUserSessions"
	LoginOperation                     OperationName = "Login"
	NewDiscordOperation                OperationName = "NewDiscord"
	NewDiscordCallbackOperation        OperationName = "NewDiscordCallback"
	NewLobbyOperation                  OperationName = "NewLobby"
	NewMultiplayerRoundOperation       OperationName = "NewMultiplayerRound"
	NewSingleplayerGameOperation       OperationName = "NewSingleplayerGame"
	NewSingleplayerRoundOperation      OperationName = "NewSingleplayerRound"
	NewYandexOperation                 OperationName = "NewYandex"
	NewYandexCallbackOperation         OperationName = "NewYandexCallback"
	RefreshTokensOperation             OperationName = "RefreshTokens"
	RegisterOperation                  OperationName = "Register"
	UpdateUserOperation                OperationName = "UpdateUser"
	UpdateUserAvatarOperation          OperationName = "UpdateUserAvatar"
	YandexLoginOperation               OperationName = "YandexLogin"
	YandexLoginCallbackOperation       OperationName = "YandexLoginCallback"
)
