// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
	"net/http"
	"strings"

	"github.com/go-faster/errors"

	"github.com/ogen-go/ogen/ogenerrors"
)

// SecurityHandler is handler for security parameters.
type SecurityHandler interface {
	// HandleBearer handles Bearer security.
	// JWT authentication. Format: `Authorization: Bearer <access-token>`. Token can be obtained from
	// `/v1/auth/login`.
	HandleBearer(ctx context.Context, operationName OperationName, t Bearer) (context.Context, error)
}

func findAuthorization(h http.Header, prefix string) (string, bool) {
	v, ok := h["Authorization"]
	if !ok {
		return "", false
	}
	for _, vv := range v {
		scheme, value, ok := strings.Cut(vv, " ")
		if !ok || !strings.EqualFold(scheme, prefix) {
			continue
		}
		return value, true
	}
	return "", false
}

var operationRolesBearer = map[string][]string{
	DeleteDiscordOperation:              []string{},
	DeleteUserSessionOperation:          []string{},
	DeleteYandexOperation:               []string{},
	EndSingleplayerGameOperation:        []string{},
	EndSingleplayerRoundOperation:       []string{},
	GetLobbiesOperation:                 []string{},
	GetLobbyOperation:                   []string{},
	GetMultiplayerGameOperation:         []string{},
	GetMultiplayerGameGuessesOperation:  []string{},
	GetMultiplayerRoundOperation:        []string{},
	GetOAuthProvidersOperation:          []string{},
	GetPrivateProfileOperation:          []string{},
	GetPublicProfileOperation:           []string{},
	GetSingleplayerGameOperation:        []string{},
	GetSingleplayerGameGuessesOperation: []string{},
	GetSingleplayerGamesOperation:       []string{},
	GetSingleplayerRoundOperation:       []string{},
	GetUserSessionsOperation:            []string{},
	NewDiscordOperation:                 []string{},
	NewLobbyOperation:                   []string{},
	NewMultiplayerRoundOperation:        []string{},
	NewSingleplayerGameOperation:        []string{},
	NewSingleplayerRoundOperation:       []string{},
	NewYandexOperation:                  []string{},
	UpdateUserOperation:                 []string{},
	UpdateUserAvatarOperation:           []string{},
}

func (s *Server) securityBearer(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t Bearer
	token, ok := findAuthorization(req.Header, "Bearer")
	if !ok {
		return ctx, false, nil
	}
	t.Token = token
	t.Roles = operationRolesBearer[operationName]
	rctx, err := s.sec.HandleBearer(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// Bearer provides Bearer security value.
	// JWT authentication. Format: `Authorization: Bearer <access-token>`. Token can be obtained from
	// `/v1/auth/login`.
	Bearer(ctx context.Context, operationName OperationName) (Bearer, error)
}

func (s *Client) securityBearer(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.Bearer(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"Bearer\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
