// Code generated by ogen, DO NOT EDIT.
package api

type DeleteDiscordRes interface {
	deleteDiscordRes()
}

type DeleteUserSessionRes interface {
	deleteUserSessionRes()
}

type DeleteYandexRes interface {
	deleteYandexRes()
}

type DiscordLoginCallbackRes interface {
	discordLoginCallbackRes()
}

type EndSingleplayerGameRes interface {
	endSingleplayerGameRes()
}

type EndSingleplayerRoundRes interface {
	endSingleplayerRoundRes()
}

type GetLobbiesRes interface {
	getLobbiesRes()
}

type GetLobbyRes interface {
	getLobbyRes()
}

type GetMultiplayerGameGuessesRes interface {
	getMultiplayerGameGuessesRes()
}

type GetMultiplayerGameRes interface {
	getMultiplayerGameRes()
}

type GetMultiplayerRoundRes interface {
	getMultiplayerRoundRes()
}

type GetOAuthProvidersRes interface {
	getOAuthProvidersRes()
}

type GetPrivateProfileRes interface {
	getPrivateProfileRes()
}

type GetPublicProfileRes interface {
	getPublicProfileRes()
}

type GetSingleplayerGameRes interface {
	getSingleplayerGameRes()
}

type GetSingleplayerGameRoundsRes interface {
	getSingleplayerGameRoundsRes()
}

type GetSingleplayerGamesRes interface {
	getSingleplayerGamesRes()
}

type GetSingleplayerRoundRes interface {
	getSingleplayerRoundRes()
}

type GetUserSessionsRes interface {
	getUserSessionsRes()
}

type LoginRes interface {
	loginRes()
}

type NewDiscordCallbackRes interface {
	newDiscordCallbackRes()
}

type NewDiscordRes interface {
	newDiscordRes()
}

type NewLobbyRes interface {
	newLobbyRes()
}

type NewMultiplayerRoundRes interface {
	newMultiplayerRoundRes()
}

type NewSingleplayerGameRes interface {
	newSingleplayerGameRes()
}

type NewSingleplayerRoundRes interface {
	newSingleplayerRoundRes()
}

type NewYandexCallbackRes interface {
	newYandexCallbackRes()
}

type NewYandexRes interface {
	newYandexRes()
}

type RefreshTokensRes interface {
	refreshTokensRes()
}

type RegisterRes interface {
	registerRes()
}

type UpdateUserAvatarRes interface {
	updateUserAvatarRes()
}

type UpdateUserRes interface {
	updateUserRes()
}

type YandexLoginCallbackRes interface {
	yandexLoginCallbackRes()
}
